### ISSUE TITLE
Failing __tests__/no-$ref-siblings.test.ts

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/spectral-openapi#1]
```
 FAIL  __tests__/no-$ref-siblings.test.ts
  ● Rule no-$ref-siblings › $ref siblings are present

    expect(received).toEqual(expected) // deep equality

    - Expected  - 34
    + Received  +  1

    - Array [
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "responses",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "responses",
    -       "300",
    -       "description",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "responses",
    -       "300",
    -       "abc",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "openapi",
    -     ],
    -     "severity": 0,
    -   },
    - ]
    + Array []

      36 |             : JSON.stringify(testCase.document);
      37 |         const errors = await s.run(doc);
    > 38 |         expect(errors.filter(({ code }) => code === ruleName)).toEqual(
         |                                                                ^
      39 |           testCase.errors.map(
      40 |             (error) => expect.objectContaining(error) as unknown
      41 |           )

      at __tests__/__helpers__/helper.ts:38:64

  ● Rule no-$ref-siblings › $ref siblings in a oas2 document

    expect(received).toEqual(expected) // deep equality

    - Expected  - 47
    + Received  +  1

    - Array [
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "securityDefinitions",
    -       "apikey",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -       "post",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -       "get",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "code": "no-$ref-siblings",
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -       "get",
    -       "security",
    -     ],
    -     "severity": 0,
    -   },
    - ]
    + Array []

      36 |             : JSON.stringify(testCase.document);
      37 |         const errors = await s.run(doc);
    > 38 |         expect(errors.filter(({ code }) => code === ruleName)).toEqual(
         |                                                                ^
      39 |           testCase.errors.map(
      40 |             (error) => expect.objectContaining(error) as unknown
      41 |           )

      at __tests__/__helpers__/helper.ts:38:64

  ● Rule no-$ref-siblings › $ref siblings in a oas3 document

    expect(received).toEqual(expected) // deep equality

    - Expected  - 47
    + Received  +  1

    - Array [
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "components",
    -       "securityDefinitions",
    -       "apikey",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -       "post",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -       "get",
    -     ],
    -     "severity": 0,
    -   },
    -   ObjectContaining {
    -     "message": "$ref must not be placed next to any other properties",
    -     "path": Array [
    -       "paths",
    -       "/path",
    -       "get",
    -       "security",
    -     ],
    -     "severity": 0,
    -   },
    - ]
    + Array []
```

**Comment by philsturgeon** [comment]
Fixed in 38db221
